[package]
name = "assertion_catalog"
version = "0.1.0"
edition = "2021"

[lib]
name = "assertion_catalog"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = {version = "2.0", features = ["extra-traits"]}
quote = "1.0"
