name: Publish Crate

on:
  workflow_dispatch:
  
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      with:
        toolchain: stable

    - run: cargo publish --dry-run --token ${CRATES_TOKEN} -p antithesis_sdk
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}