name: Publish Crate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Is this a dry-run?'
        required: true
        default: true
        type: boolean
  
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      with:
        toolchain: stable
    
    - name: Cargo Publish (Dry Run)
      if:  ${{ inputs.dry-run == true || inputs.dry-run == 'true' }} 
      run: cargo publish --dry-run --token ${CRATES_TOKEN} -p antithesis_sdk
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Cargo Publish
      if:   ${{ inputs.dry-run != true && inputs.dry-run != 'true' }} 
      run: echo we will publish for real
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
